### ISSUE TITLE
Template Inheritance list

### ISSUE THREAD

**Issue by Bazmech** [DanDiplo/Umbraco.GodMode#10]
Umbraco version 7.11.0 assembly: 1.0.6743.18592

This may or may not be an issue and simply how you want it to work but when viewing the template list and expanding one a reference to itself appears in the inheritance list.

If it is to be left in there so that you always have the option to click on it to edit the template then fine but the order of inheritance could then be changed to show in the correct order. The image below is 3 levels of templates but for me 'Master' or 'Test for Inheritance' should move to the bottom 

![image](https://user-images.githubusercontent.com/38332224/41780870-de8879dc-762d-11e8-91f4-f4965ce0afa3.png)

**Comment by DanDiplo** [comment]
This is basically down to the way Umbraco returns the order - I don't have any control over it. It should, however, show the hierarchy from the current template (first) back up to the top "master" template.

What is the order of inheritance on those templates? 

In all the tests I've done Umbraco returns these correctly and it shows in a logical order. For instance, on my 7.11.0 test site I have a template called Article, that inherits from _Two Column Master which in turn inherits from __Master. It shows like this:

![image](https://user-images.githubusercontent.com/6676168/41781348-2d00eab2-762f-11e8-85bd-d0965cf5caaf.png)

This is what I intended and it seems to work in all tests I've made.

**Comment by Bazmech** [comment]
The correct order should be 

- Test for inheritance
- Blog
- Master

If i add underscores tot he names as you have then they come back in the correct order.

Just using normal names but with the level as a number on the end I get this at level's 3 and 4,
![image](https://user-images.githubusercontent.com/38332224/41785771-81aba2da-763b-11e8-9b7c-71e56671f66c.png)

to be honest it isn't a massive issue, especially if this is comign straight from the system, as you should know your structure but I would still use this to get to templates quickly. I'm happy for you to close this if it's simply out of your control.

**Comment by DanDiplo** [comment]
Ahh, I see now. Umbraco must somehow sort them alphabetically or something (as I reverse the order). Unfortunately, I can't do much about this. Umbraco basically returns a `Path` string which is a CSV of IDs, such as `"1,32,454"` and I just convert those IDs to template objects. But there's no other information I can use to determine the actual hierarchy (that I know of). I'll bear it in mind, but for now I can't see a way of fixing it.

**Comment by Bazmech** [comment]
I had a quick delve into the code and think that i may have found an answer. My code has just been thrown in, so i'm not submitting this as a pull request, and it's getting late so i'm sure you can make it slicker.

I used the path to order the list or parent templates. So file UmbracoDataService.cs line 190 i changed

`Parents = templates.Where(t => template.Path.Split(',').Select(x => Convert.ToInt32(x)).Contains(t.Id)).Select(t => new TemplateModel(t)).OrderBy(d => template.Path.Split(',').IndexOf(d.Id.ToString()))`

**Comment by DanDiplo** [comment]
Cool, I'll try it out and if it works OK then I'll include it in the next release. Cheers for your help!

**Comment by DanDiplo** [comment]
Hi! It's been a while, but I've had reason to release a new version (1.5.1) and I've incorporated your template ordering code into it. It's currently on NuGet -https://www.nuget.org/packages/Diplo.GodMode/1.5.1

Thanks for your contribution!
