### ISSUE TITLE
Can't find it in the CMS

### ISSUE THREAD

**Issue by StefanoChiodino** [DanDiplo/Umbraco.GodMode#14]
I installed v1.5.1 but also tried v1.5.0.

I can see the dll in the bin folder, I can see the files in the App_Plugin folder, and the network tab shows them being loaded.

Yet I can't see the tab in the CMS, under the developer section and can't think of a reason why!

Umbraco v 7.13.2

**Comment by DanDiplo** [comment]
Hi. How did you install it? Via an Umbraco package or via NuGet? 

Are you using any form of dependency injection, as that has been known to cause issues? And have you tried restarting the site? Are there any errors in the trace log files in `/App_Data/Logs`?

**Comment by StefanoChiodino** [comment]
Hi!

Nuget, always.

Yes, we are using DI. Could be structure map.

I'll have a look into the logs.

Thanks!

**Comment by DanDiplo** [comment]
Yeah, I think it definitely is DI related. Not sure why it happens, but there's a similar thread about DI here that might help you: See https://github.com/DanDiplo/Umbraco.GodMode/issues/13

**Comment by StefanoChiodino** [comment]
Thanks, I'll give that a go!

**Comment by StefanoChiodino** [comment]
I was just missing the line in `trees.config`! No idea why it didn't get there, but didn't have to do anything with structure map!
