### ISSUE TITLE
Feature request, add "bump clientdependency version" button to utilities

### ISSUE THREAD

**Issue by skttl** [DanDiplo/Umbraco.GodMode#15]

**Comment by DanDiplo** [comment]
Hi @skttl That's a very good idea, I'll definitely look at that for the next release. Thanks for the suggestion!

**Comment by skttl** [comment]
Happy to submit a PR, if you want :)

**Comment by DanDiplo** [comment]
PR's are always welcome, though don't feel obliged! I might try and gather a few more ideas for a release, so if you have any more suggestions...
