### ISSUE TITLE
Use editorService for links in browsers

### ISSUE THREAD

**Issue by skttl** [DanDiplo/Umbraco.GodMode#16]
![billede](https://user-images.githubusercontent.com/3726467/65235117-4959f700-dad6-11e9-86dc-555b14dc227e.png)

This link opens a new window, it would be sweet if it could just open a new infinite editor instead.

I think this is pretty easy at least for doctypes and datatypes. Not sure how easy for internal GodMode stuff.

I'm going to take a crack at it "some time" :)

**Comment by DanDiplo** [comment]
That's a fantastic idea; I'd never thought of that. I'd been so busy porting across from v7 I never considered it could be done better in 8. I'd be really happy for you to have a go at this, if you find time!

**Comment by Bazmech** [comment]
great work on this @skttl 

This package is a must-have. So glad to see  continual improvements
