### ISSUE TITLE
Cannot sort images by size

### ISSUE THREAD

**Issue by HistoricEnglandDigitalTeam** [DanDiplo/Umbraco.GodMode#21]
Not really a bug, but we are missing the ability in the v8 God Mode to filter media images by file size and type. This was really appreciated in v7  as  we use it to identify and weed out large image files. 

Any chance of you bringing this back again please?

And a small point, the version number is not easily visible alongside the package name any more.

**Comment by DanDiplo** [comment]
Hi. Yeah, I wish I could have implemented it for v8, but there are technical reasons why it wasn't possible as they changed the underlying Media service in Umbraco. Without getting into technicalities, the size of Media isn't returned by the Media service when you get a paginated list of media - you can only work it out once you get the item. So I can't order by it using the Media service, as it's not present until I look-it. Not sure if that makes sense, but I couldn't find a way of doing it. Sorry!

**Comment by HistoricEnglandDigitalTeam** [comment]
That's a shame. Thanks for your fast response. Is it technically possible to bring it back in  v9?

**Comment by DanDiplo** [comment]
From what I've seen the APIs in v9 are basically the same as v8, so I'd imagine not. But I am currently working on the v9 version, so will certainly be looking into whether it's possible and will give some thought on how it could be done.

**Comment by HistoricEnglandDigitalTeam** [comment]
Great, thanks.
