### ISSUE TITLE
Global Settings : DefaultUILanguage issue

### ISSUE THREAD

**Issue by craigs100** [DanDiplo/Umbraco.GodMode#25]
Umbraco V9.1.2 with en-GB being the only language available in the Settings: Languages section and on a machine with only en-GB installed in the OS. The Global Settings : DefaultUILanguage key shows a value of "en-US".  I just wondered where it gets it from?

**Comment by DanDiplo** [comment]
Hi Craig. It reads it from the Umbraco Global Settings variable, namely: `Umbraco.Cms.Core.Configuration.Models.GlobalSettings`. This is loaded by getting an instance of it via the DI factory:

`var globalSettings = factory.GetRequiredService<IOptions<GlobalSettings>>();`

I then use reflection to output the values of all the properties in the class. So it just reads the value from the `DefaultUILanguage` property of this class.

I did note that in the `GlobalSettings` class there is `internal const string StaticDefaultUILanguage = "en-US";` so I imagine that is what you are seeing. So I guess that property just holds the default "fallback" value. I'm not really sure how this is used by Umbraco, though.

**Comment by craigs100** [comment]
I suppose this is the "real" default for installation. The default will change per user I guess.

Thanks Dan
