### ISSUE TITLE
Usage count

### ISSUE THREAD

**Issue by tompipe** [DanDiplo/Umbraco.GodMode#3]
Usage counts seem to be incorrect. 

Items show 1 in the list...
![image](https://user-images.githubusercontent.com/629719/27308222-61394d6c-5545-11e7-88aa-fa33431014e4.png)

But clicking in to find usage, shows there are none...
![image](https://user-images.githubusercontent.com/629719/27308244-74f7b140-5545-11e7-976b-a98f42988717.png)

**Comment by DanDiplo** [comment]
Hi Tom,

Thanks for reporting. It's a strange one, as I can't seem to replicate in any Umbraco instances I've tried. I return the data using an SQL query (for performance). If you have access to SQL Server could you try executing the following query and see what results you get:

```
SELECT N.Id, N.ParentId, N.Level, CT.icon, N.Trashed, CT.alias, D.Text as Name, N.createDate, D.updateDate, Creator.Id AS CreatorId, Creator.userName as CreatorName, Updater.Id as UpdaterId, Updater.userName as UpdaterName
FROM cmsContent C
INNER JOIN umbracoNode N ON N.Id = C.nodeId
INNER JOIN cmsContentType CT ON C.contentType = CT.nodeId
INNER JOIN cmsDocument D ON D.nodeId = C.nodeId
INNER JOIN umbracoUser AS Creator ON Creator.Id = N.nodeUser
INNER JOIN umbracoUser AS Updater ON Updater.Id = D.documentUser
WHERE D.Newest = 1 
AND CT.alias = 'blockImage'
```
This is essentially what the filter is doing. If you are able, could you play around with the query, maybe trying removing some joins and seeing if any of them are to blame? Try removing the `WHERE D.Newest = 1` clause, for instance.

One outside possibility is there is some minor corruption in your DB. Umbraco should mark the most recent version of any content as the current version by setting the 'newest' flag to 1. But I've occasionally seen it fail to do this.

Let me know if you can find anything to help pinpoint the issue. Thanks!

**Comment by pedroadaodev** [comment]
Hi,

I have the same error.
![image](https://user-images.githubusercontent.com/10515084/54142164-0cbe8c00-441f-11e9-9f8a-3eaaee250b72.png)

and the query
![image](https://user-images.githubusercontent.com/10515084/54142202-21028900-441f-11e9-9e7c-ea82821ffbf2.png)

Is there anything that a can do to help with this error?

This is a Umbraco 7.13.2, upgraded from 7.3.x (I think). Diplo God Mode 1.5.1

Thanks,
Pedro

**Comment by DanDiplo** [comment]
Hi pedro. It's hard for me to replicate or diagnose without having your database, as it works OK for me (and most people). I suspect that a join in the SQL isn't working - which could be a fault in my logic or an issue in the Umbraco tables (ie. if a user has been deleted that owned a node this would happen).

Are you able to play around with the SQL and see if removing the `D.Newest = 1` makes any difference? Or try tweaking it to see if you can get the expected result and then let me know the SQL you have?

**Comment by pedroadaodev** [comment]
Hi @DanDiplo 
See if this helps. 

![image](https://user-images.githubusercontent.com/10515084/54207117-844cf380-44d1-11e9-8805-145f0f30dd45.png)

And your query
![image](https://user-images.githubusercontent.com/10515084/54207178-a0509500-44d1-11e9-8dd9-a63ae8c7bec5.png)

and the Umbraco BO
![image](https://user-images.githubusercontent.com/10515084/54207561-44d2d700-44d2-11e9-9d2f-8e83c742e86c.png)

I've double check the connection string, just in case... :)

What can I do next to help you?

Best regards,
Pedro

**Comment by DanDiplo** [comment]
I guess the next thing would to be add in the joins to see which join is making the query fail.

What does the following return?

```
SELECT N.Id, N.ParentId, N.Level, CT.icon, N.Trashed, CT.alias
FROM cmsContent C
INNER JOIN umbracoNode N ON N.Id = C.nodeId
INNER JOIN cmsContentType CT ON C.contentType = CT.nodeId
AND CT.alias = 'appBlock'
```

Could you add back each join condition in turn to try and see where it is failing? It could be something isn't correctly linked in your database...

**Comment by pedroadaodev** [comment]
No results with that query.

I could find some results with this one, but the totals of "annex" are wrong
![image](https://user-images.githubusercontent.com/10515084/54270584-a00ad500-4577-11e9-8e5e-8fa782ca9866.png)

**Comment by DanDiplo** [comment]
It kind of sounds to me like something has gone wrong in your Umbraco database somewhere if they aren't joining (or I'm making some fundamental flaw in my assumptions as to how it works).

I'm guessing your counts are wrong because you can have multiple versions of a piece of content in umbraco (the node update history), so that's why my original query had `D.Newest` = 1 so it only gets the current version.

**Comment by DanDiplo** [comment]
I've made a change to this, which I think now corrects any issues.
