### ISSUE TITLE
Feature Request: Add "Count" info on dashboards 

### ISSUE THREAD

**Issue by hfloyd** [DanDiplo/Umbraco.GodMode#30]
Hi @DanDiplo, 
Very cool tool! I was thinking it would be really helpful to have a "Count" value displayed on the various dashboards - especially when doing a search or filter operation, it would be great to see a quantity returned.

**Comment by DanDiplo** [comment]
@hfloyd Y'know, that's not a bad idea, Heather - I'll definitely try and include this in the next release! 

Out of interest, are you using v9 or v8 or both? I'm not sure whether to keep v8 updated or just to concentrate on v9...

**Comment by hfloyd** [comment]
Thanks, @DanDiplo ! I'm using v9. 😊

**Comment by DanDiplo** [comment]
Hi Heather. I've just released `9.2.3` which has the count (where relevant). Let me know what you think!

**Comment by hfloyd** [comment]
It looks great -  Thanks!
