### ISSUE TITLE
App_Plugins folder isn't included in build

### ISSUE THREAD

**Issue by rickbutterfield** [DanDiplo/Umbraco.GodMode#33]
When adding the v10 package to a v10 site, no files are copied from the NuGet cache because they don't exist:

Visual Studio Mac error:
<img width="1099" alt="image" src="https://user-images.githubusercontent.com/200450/176021319-dd457df3-2781-49a4-8e32-7f03c345b90d.png">

10.0.0 folder in cache:
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/200450/176021519-c95ecd69-215b-4d1a-921e-f7ceeea217a7.png">

9.2.3 folder for comparison (contains `App_Plugins`):
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/200450/176021496-9a7fba1a-5fd7-4137-a800-54486d29df59.png">

**Comment by DanDiplo** [comment]
Darn, I tested this, but I guess the files must have already been there from previous tests! Thanks for spotting!

**Comment by DanDiplo** [comment]
BTW, I've delisted 10.0.0 and added 10.0.1 with this fix (you get a credit :p) - https://www.nuget.org/packages/Diplo.GodMode/#release-body-tab
