### ISSUE TITLE
DataType browser isUsed does not look at Media Types

### ISSUE THREAD

**Issue by timbo04** [DanDiplo/Umbraco.GodMode#4]
Hi Dan,
Love GodMode, very useful.  Unfortunately I removed a data type which was only used as a property in a Media Type.  It was incorrectly reported as unused.
No harm done, site is still in development!
Using v1.3.7 with Umbraco 7.6.2
Tim

**Comment by timbo04** [comment]
The issue is within GetDataTypesStatus
The usedPropertyTypes is only set from GetAllContentTypes, it also needs to take GetAllMediaTypes into account.  Something like this:

`var mediaTypes = cts.GetAllMediaTypes();`
`var usedPropertyTypes = contentTypes.SelectMany(x => ` 
`x.PropertyTypes.Concat(x.CompositionPropertyTypes))
                .Union(mediaTypes.SelectMany(x => x.PropertyTypes.Concat(x.CompositionPropertyTypes)));`

Tim

**Comment by DanDiplo** [comment]
Hi Tim. Thanks for the feedback!

TBH I don't think I ever considered media types when creating God Mode. But it make sense to include them. Thanks for the code suggestion (I love it when someone posts a fix for an issue!), I'll check it out and then incorporate it into the next release.

**Comment by DanDiplo** [comment]
Hi. I've released [1.3.9](https://www.nuget.org/packages/Diplo.GodMode/1.3.9) which should incorporate your suggested fix to include media types. It seems to work in my limited tests. I'll close this for now, but let me know if you have any issues or comments.
