### ISSUE TITLE
Debug mode in Nuget

### ISSUE THREAD

**Issue by Matthew-Wise** [DanDiplo/Umbraco.GodMode#40]
Hi Dan,

I noticed while debugging a memory issue (not related to your package). The the dll included in the nuGet release is in Debug mode 

![image](https://github.com/DanDiplo/Umbraco.GodMode/assets/6782865/92f9dc7c-b837-4030-9c20-bf327bde7a66)

Checked using nuget.info - 
https://nuget.info/packages/Diplo.GodMode/10.3.0
https://nuget.info/packages/Diplo.GodMode/10.2.2

Happy to help, create a pipeline in Github if you want it 

Thanks
Matt

**Comment by Matthew-Wise** [comment]
Noticed in the readme your using dotnet pack looks like Microsoft messed you about as it used default to debug

https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/8.0/dotnet-pack-config Article 02/08/2023

**Comment by DanDiplo** [comment]
Well, I never knew that. I'd just assumed it would be release! Thanks for spotting. 

I'll look into this and see if I can release a new version with release mode. Darn.

**Comment by Matthew-Wise** [comment]
I only found out when I noticed your readme and was confused so looked it up :D

**Comment by DanDiplo** [comment]
I live and learn :) Anyway, a new version has been released in, erm, release mode!

https://nuget.info/packages/Diplo.GodMode/10.3.1

Thanks again for spotting this and helping to resolve.
