### ISSUE TITLE
Hide sections/groups

### ISSUE THREAD

**Issue by daanbakker1995** [DanDiplo/Umbraco.GodMode#41]
Hello there,

Is there a way to hide certain parts of Godmode? For example, what if I wanted to hide the 'Diagnostics' section or maybe a group in there like 'Database Settings'? Is see no option or configuration to turn off or hide sections and or groups.

Greetings,
Daan

**Comment by DanDiplo** [comment]
Hi. No, I'm afraid there's no option, other than forking the code. I think you are the first to mention this, so not something I'd thought about. I can think about adding for any new release, though....

**Comment by Jonroberts24Swansea** [comment]
Hi
Our client would like to hide sections depending on Group permissions too. Their PEN testers failed GodMode as it showed the Connection String to the database

**Comment by DanDiplo** [comment]
@Jonroberts24Swansea As GodMode is only available in `Settings` section of Umbraco then it would only be accessible to users given access to this section, so I'm not clear how Group permissions would apply? 

But I'll give some through to hiding sections / groups - it would probably be a binary thing, though, as I don't think groups will work.

**Comment by DanDiplo** [comment]
Hi again. I've given this some thought and come up with a solution I hope will work for you. It is in the [10.3.2 release](https://www.nuget.org/packages/Diplo.GodMode/10.3.2). It allows you to hide an entire tree branch (eg. all Diagnostics) but you can also remove groups and sections in the diagnostics or redact individual diagnostic keys. So, for instance, you could redact the DB connection string, but still allow the rest.

You will need to add a new setting in `appSettings.json` which I've detailed in the readme below

https://github.com/DanDiplo/Umbraco.GodMode?tab=readme-ov-file#hiding-features-and-diagnostics

Please test and feedback any thoughts...

**Comment by Jonroberts24Swansea** [comment]
Great - thank you so much Dan - I'll give it a go. Thanks for all your help

**Comment by DanDiplo** [comment]
Not had any feedback of issues so will close this.
