### ISSUE TITLE
v1.3.8 NuGet package contains duplicated content

### ISSUE THREAD

**Issue by ronaldbarendse** [DanDiplo/Umbraco.GodMode#5]
The NuGet package for version 1.3.8 has duplicated content, the following items should be removed:
- `content\BackOffice\*`
- `content\bin\Diplo.GodMode.dll`
- `package.manifest`

The only content should be in `content\App_Plugins\GodMode\*` and `lib\net45\Diplo.GodMode.dll`.

Since it is duplicated, the files/directories listed above can be safely removed from the project (where the package is installed to). After releasing a patched version to NuGet, you could unlist this version, so others won't run into this problem 👍

**Comment by DanDiplo** [comment]
Ahh, thanks. The automated build process had changed a bit, so it will be down to that. Thanks for reporting!

**Comment by DanDiplo** [comment]
Hi again. The should now be fixed in 1.3.9 - https://www.nuget.org/packages/Diplo.GodMode/1.3.9
I've delisted 1.3.8.
Thanks again for reporting and sorry for any inconvenience. Let me know if this version is OK.

**Comment by ronaldbarendse** [comment]
Hi Dan, thanks for solving it so quickly! And great work on this package (and the others too)!
