### ISSUE TITLE
Package's "use strict" can cause issues with other packages

### ISSUE THREAD

**Issue by number45** [DanDiplo/Umbraco.GodMode#6]
I found when using God Mode on a site that also used newsletter studio I kept getting the error "Strict mode code may not include a with statement" when client dependency is switched on.

I believe this may be due to the "use strict" being set globally which, when the scripts are merged together by client dependency, is causing issues with any package that uses something that isn't supported in strict mode (in newsletter studio's case it was _with_).

**Comment by DanDiplo** [comment]
Hi. Thanks for highlighting this. I hadn't realised how the bundling would make this apply out of scope of my package. I will look at addressing this in the next release.

If you wish to implement a quick fix then you could go into `/App_Plugins/GodMode/BackOffice/Scripts` and remove the "use strict" directive from the javascript there (then clear out the Client Dependency files).

I'd also maybe inform Newsletter Studio that their package doesn't work in strict mode - which is something it probably should do.

**Comment by DanDiplo** [comment]
@number45 I've just released a new version that should fix this problem.  Let me know if it does!

Available on NuGet and Our:

https://www.nuget.org/packages/Diplo.GodMode/

https://our.umbraco.org/projects/developer-tools/diplo-god-mode/

**Comment by number45** [comment]
Thanks @DanDiplo That seems to have fixed the issue.
