### ISSUE TITLE
HTML files not found

### ISSUE THREAD

**Issue by ruant** [DanDiplo/Umbraco.GodMode#7]
Running Umbraco version 7.6.6 assembly: 1.0.6456.19226

After installation I get this on all menu items under God Mode:

```
Request error: The URL returned a 404 (not found): 
views/godModeTree/mediaBrowser.html
```

Not just this one, but on all of them.
I do see the files HTML files in the App_Plugin folder tho.
But the files are trying to be loaded from:
`http://webpage.local/umbraco/views/godModeTree/mediaBrowser.html?umb__rnd=a2e240ac487b4fa3ded7abfee58a6c71`

**Comment by DanDiplo** [comment]
Hmm, that's a strange one - I've never seen this before. The correct path should be:

http://webpage.local/App_Plugins/GodMode/backoffice/godModeTree/mediaBrowser.html

You should see the following URL in browser:

http://webpage.local/umbraco/#/developer/godModeTree/mediaBrowser/browse

Maybe try clearing the Client Dependency cache and forcing a reload in browser (F5). Can you run in debug mode in web.config (this disables Client Dependency)?

Is there any customised about your Umbraco that could be changing paths?

I've installed the package on lots of versions of Umbraco and never had this issue!

**Comment by ruant** [comment]
Bumping the Client Dependency version number did the trick.
Else it just needed the night to sort it self out... 🤣 

Cheers Dan for the quick reply!
High five✋
