### ISSUE TITLE
Server Error on clicking on Edit for a template

### ISSUE THREAD

**Issue by Bazmech** [DanDiplo/Umbraco.GodMode#8]
Umbraco version 7.11.0 assembly: 1.0.6743.18592

When clicking on Edit for a template either in Doc type browser or Template browser in the right hand frame you get a server error.

An example link that causes the error is 

http://localhost:4313/umbraco/#/settings/framed/settings%252FViews%252FEditView.aspx%253FtreeType%253Dtemplates%2526templateID%253D1060

but i can see that editing a template browsing normally  would be

http://localhost:4313/umbraco/#/settings/templates/edit/1060

I've only just come across your plugin, and frankly it's great, but i'm under no pretense that this is the answer or won't break compatibility with previous versions of Umbraco, as I don't know it well enough, but i'll see what i can do to help out.

**Comment by DanDiplo** [comment]
Hi Barry,

Thanks, you are right! They must have changed the path in one of the more recent versions of Umbraco.

I guess I'll need to try and figure out which is the lowest version where this changed and then change the path and update the dependency.

If you can help figure out which version this changed happened in, that would help!

**Comment by Bazmech** [comment]
Hi Dan

To test i installed a previous version of Umbraco and the URL's being used are like my example fix url. i installed everything through NuGet and went back and checked versions on the latest Umbraco install i did. For Umbraco 7.11 it installed V1.4 of GodMode but now it is allowing me to install V1.5. Not sure if another dependency was holding this back but i will re-check all the issues that I have submitted and change appropriately. i'll try another base install and see what happens this time.

**Comment by DanDiplo** [comment]
I figured out that Umbraco 7.6.0 was the version where the template (and partial) paths had changed so I've updated the NuGet package to fix this - this is why you are now seeing v1.5.0 in NuGet now :) I've literally just released it! 

So if you update (and maybe clear cache) this should fix those issues.

**Comment by Bazmech** [comment]
Hi Dan

That's fixed all the server issues. Just getting up to V1.5 was the issue. I'll close the other issues. I've also added project compatibility on https://our.umbraco.org

Great tool when you have a mass of components or simply want to know whats used where.
